spring:
  application:
    name: smartFarm
  mvc:
    view:
      suffix: .html

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password:
